models/ContactForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

/**
 * ContactForm is the model behind the contact form.
 */
class ContactForm extends Model
{
    public $name;
    public $email;
    public $subject;
    public $body;
    public $verifyCode;

    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            // name, email, subject and body are required
            [['name', 'email', 'subject', 'body'], 'required'],
            // email has to be a valid email address
            ['email', 'email'],
            // verifyCode needs to be entered correctly
            ['verifyCode', 'captcha'],
        ];
    }

    /**
     * @return array customized attribute labels
     */
    public function attributeLabels()
    {
        return [
            'verifyCode' => 'Verification Code',
        ];
    }

    /**
     * Sends an email to the specified email address using the information collected by this model.
     * @param  string  $email the target email address
     * @return boolean whether the model passes validation
     */
    public function contact($email)
    {
        if ($this->validate()) {
            Yii::$app->mailer->compose()
                ->setTo($email)
                ->setFrom([$this->email => $this->name])
                ->setSubject($this->subject)
                ->setTextBody($this->body)
                ->send();

            return true;
        } else {
            return false;
        }
    }
}

models/Gallery.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "gallery".
 *
 * @property integer $id
 * @property string $name
 * @property string $created_time
 * @property integer $likes
 * @property string $source
 *
 * @author Lidiexy Alonso <lidiexy@gmail.com>
 * @link https://bitbucket.org/lidiexy/fbtaskbe/
 */
class Gallery extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName(){
        return 'gallery';
    }

    /**
     * @inheritdoc
     */
    public function rules(){
        return [
            [['id', 'created_time', 'source'], 'required'],
            [['id', 'likes'], 'integer'],
            [['created_time'], 'safe'],
            [['source'], 'string'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels(){
        return [
            'id' => 'ID',
            'name' => 'Name',
            'created_time' => 'Created Time',
            'likes' => 'Likes',
            'source' => 'Source',
        ];
    }
}

models/SearchGallery.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use app\models\Gallery;

/**
 * SearchGallery represents the model behind the search form about `app\models\Gallery`.
 */
class SearchGallery extends Gallery
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'likes'], 'integer'],
            [['name', 'created_time', 'source'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function scenarios()
    {
        // bypass scenarios() implementation in the parent class
        return Model::scenarios();
    }

    /**
     * Creates data provider instance with search query applied
     *
     * @param array $params
     *
     * @return ActiveDataProvider
     */
    public function search($params)
    {
        $query = Gallery::find();

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 42
            ],
        ]);

        $this->load($params);

        if (!$this->validate()) {
            // uncomment the following line if you do not want to return any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }

        $query->andFilterWhere([
            'id' => $this->id,
            'created_time' => $this->created_time,
            'likes' => $this->likes,
        ]);

        $query->andFilterWhere(['like', 'name', $this->name])
            ->andFilterWhere(['like', 'source', $this->source]);

        return $dataProvider;
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\helpers\Url;
use yii\web\Controller;
use app\models\ContactForm;
use app\models\Gallery;
use app\models\SearchGallery;
use yii\web\NotFoundHttpException;

class SiteController extends Controller
{
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex() {
        //The basic behavior for Gridview Index
        $searchModel = new SearchGallery();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        Url::remember();
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionDetail($id) {
        if (($model = Gallery::findOne($id)) !== null) {
            return $this->render('detail', [
                'model' => $model,
                'lastUrl' => Url::previous(),
            ]);
        } else {
            throw new NotFoundHttpException('The requested detail page does not exist.');
        }
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/layouts/main.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    <?php $this->head() ?>
</head>
<body>

<?php $this->beginBody() ?>
    <div class="wrap">
        <?php
            NavBar::begin([
                'brandLabel' => '<img src= "images/vanderbilt-64x50.png" class="img-responsive brand-logo"> Vanderbilt Facebook Gallery',
                'brandUrl' => Yii::$app->homeUrl,
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top',
                ],
            ]);
            echo Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-right'],
                'items' => [
                    ['label' => 'Home', 'url' => ['/site/index']],
                    ['label' => 'About', 'url' => ['/site/about']],
                    ['label' => 'Contact', 'url' => ['/site/contact']],
                ],
            ]);
            NavBar::end();
        ?>

        <div class="container">
            <?= Breadcrumbs::widget([
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]) ?>
            <?= $content ?>
        </div>
    </div>

    <footer class="footer">
        <div class="container">
            <p class="pull-left">&copy; Vanderbilt University <?= date('Y') ?></p>
            <p class="pull-right"><?= Yii::powered() ?></p>
        </div>
    </footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/_item_view.php
<div class="item col-md-4 col-sm-6 col-xs-12">
    <div class="my-thumb base-container">
        <div class="bg-center text-center my-thumb-body" style="background-image: url('<?= $model->source; ?>')">
            <div class="row row-table">
                <div class="col-xs-12 text-white">
                    <img src="images/vanderbilt-waterstamp.png" alt="Vanderbilt" class="img-thumbnail img-circle thumb128">
                    <h3 class="non-margin">&nbsp;</h3>
                    <p class="non-margin">
                        &nbsp;
                    </p>
                </div>
            </div>
        </div>
        <div class="my-thumb-body text-center bg-vand-color">
            <div class="row row-table">
                <div class="col-xs-6 text-white text-2x">
                    <?= \yii\helpers\Html::a('View Detail', ['site/detail', 'id'=>$model->id]); ?>
                </div>
                <div class="col-xs-6 text-white text-2x">
                    <h4 class="non-margin"><?=$model->likes;?></h4>
                    <p class="non-margin text-muted">
                        <small>Likes</small>
                    </p>
                </div>
            </div>
        </div>

    </div>
</div>

views/site/about.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>
    <div class="jumbotron">
        <img src="images/vanderbilt-logo.jpg" class="img-circle" alt="Vanderbilt University" title="Vanderbilt University"/>
        <h1>Front-End Side App!</h1>
        <p>
            This Web Application was made by Lidiexy Alonso <a href="mailto:lidiexy@gmail.com">lidiexy@gmail.com</a>.
            The main goal of this application is Manage the Photo Gallery for Vanderbilt University.
            This project is the Front-End side of the programming task created by Jason Tan and colleagues.
        </p>
    </div>
</div>

views/site/contact.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

    <div class="alert alert-success">
        Thank you for contacting us. We will respond to you as soon as possible.
    </div>

    <p>
        Note that if you turn on the Yii debugger, you should be able
        to view the mail message on the mail panel of the debugger.
        <?php if (Yii::$app->mailer->useFileTransport): ?>
        Because the application is in development mode, the email is not sent but saved as
        a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
        Please configure the <code>useFileTransport</code> property of the <code>mail</code>
        application component to be false to enable email sending.
        <?php endif; ?>
    </p>

    <?php else: ?>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>
                <?= $form->field($model, 'name') ?>
                <?= $form->field($model, 'email') ?>
                <?= $form->field($model, 'subject') ?>
                <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>
                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>
                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>

    <?php endif; ?>
</div>

views/site/detail.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Gallery */

$this->title = Html::encode($model->name);
$this->params['breadcrumbs'][] = $model->id;
?>
<div class="gallery-view">
    <div class="page-header">
        <h1>Vanderbilt Photo Id <small><?= $model->id ?></small></h1>
    </div>

    <div class="bg-white text-center">
        <div class="row row-table">
            <div class="col-xs-12">
                <img class="img-resp" src="<?= $model->source; ?>" alt="<?= Html::encode($model->name); ?>" title="<?= Html::encode($model->name); ?>"/>
            </div>
        </div>
    </div>
    <div class="my-thumb-body text-center bg-info-color">
        <div class="row row-table">
            <div class="col-xs-12 text-white">
                <?= Html::encode($model->name); ?>
            </div>
        </div>
    </div>

    <div class="my-thumb-body text-center bg-vand-color">
        <div class="row row-table">
            <div class="col-xs-6 text-white text-2x">
                <h4 class="non-margin"><?=$model->likes;?></h4>
                <p class="non-margin text-muted">
                    <small>Likes</small>
                </p>
            </div>
            <div class="col-xs-6 text-white text-2x">
                <?php
                $date = DateTime::createFromFormat('Y-m-d H:i:s', $model->created_time);
                ?>
                <h4 class="non-margin"><?= $date->format('F d, Y h:ia');?></h4>
                <p class="non-margin text-muted">
                    <small>Uploaded</small>
                </p>
            </div>
        </div>
    </div>

    <div class="my-thumb-body text-center bg-link-color">
        <div class="row row-table">
            <div class="col-xs-12">
                <span class="glyphicon glyphicon-link"></span> <?= $model->source ?>
            </div>
        </div>
    </div>

    <div class="row row-table">
        <p>&nbsp;</p>
        <?= Html::a('Back to the list', $lastUrl, ['class' => 'btn btn-default']); ?>
    </div>

</div>

views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
use yii\helpers\Html;
use yii\widgets\ListView;
use kop\y2sp\ScrollPager;

/* @var $this yii\web\View */
/* @var $searchModel app\models\SearchGallery */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Vanderbilt Facebook Gallery';
?>
<div class="site-index">
    <div class="col-xs-12 gallery">
        <div class="page-header">
            <h1>Vanderbilt University <small>photos from Facebook page</small></h1>
        </div>
        <div class="list-view">
            <?php
            echo ListView::widget([
                'dataProvider' => $dataProvider,
                'itemOptions' => ['class' => 'item'],
                'itemView' => '_item_view',
                'summary' => '',
                'layout' => "{sorter}\n{items}\n{pager}",
                'pager' => [
                    'class' => ScrollPager::className(),
                    'negativeMargin' => '200',
                    'triggerText' => 'Load More Photos',
                    'triggerOffset' => 3,
                    'noneLeftText' => '',
                ],
                'sorter' => [
                    'attributes' => ['likes','created_time'],
                ]
            ]);
            ?>
        </div>
    </div>
</div>